version: '3.8'

services:
  piston_api:
    build: api
    privileged: true
    restart: always
    ports:
      - 6969:6969
    volumes: 
      - ./data/piston:/piston
      - ./repo:/repo
    tmpfs:
      - /piston/jobs

  piston_fs_repo: #Temporary solution until CI works
    build: repo
    command: ['deno-1.7.5'] # Only build deno
    volumes:
      - ./repo:/repo
      - ./packages:/packages