version: '2.7'

services:
    piston_api:
        build: api
        cap_add: 
            - CAP_SYS_ADMIN
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston:/piston
        tmpfs:
            - /piston/jobs:exec

    piston_fs_repo: # Local testing of packages
        build: repo
        command: ['dart-2.12.1'] # Only build dart
        volumes:
            - .:/piston
