version: '2.7'

services:
    piston_api:
        image: ghcr.io/engineer-man/piston
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston:/piston
        tmpfs:
            - /piston/jobs:exec
