version: '3.8'

services:
  piston_api:
    build: api
    privileged: true
    restart: always
    ports:
      - 6969:6969
    volumes: 
      - ./data/piston:/piston
      - ./repo:/repo
    tmpfs:
      - /piston/cache
      - /piston/jobs

  piston_fs_repo: #Temporary solution until CI works
    build: repo
    command: >
      bash -c '/repo/make.sh &&
      curl http://piston_api:6969/repos -XPOST -d "slug=local&url=file:///repo/index.yaml";
      echo -e "\nAn error here is fine, it just means its already added it. Perhaps you restarted this container"
      '
    volumes:
      - ./repo:/repo
      - ./packages:/packages