---

name: LXC Build

on:
  push:
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Distrobuilder
        run: sudo apt-get install -y distrobuilder
      # build container
      - name: Build Artifact
        run: sudo ./build.sh
        working-directory: container

      - name: chown everything
        run: |
          sudo chown -R runner:runner .
        working-directory: container
      
      #  Upload container 
      - uses: actions/upload-artifact@v2
        with:
          name: lxc-container
          path: |
            container/output-piston-bionic/meta.tar.xz
            container/output-piston-bionic/rootfs.tar.xz